### ISSUE TITLE
Add mtu to docker in images using docker

### ISSUE THREAD

**Issue by TheHussky** [mekstack/images#2]
Docker behaves wrongly on hosts because it doesn't  query info about host mtu.
Add
```json
 "mtu": 1300
```
to /etc/docker/daemon.json.
Check that pipelines complete successfully.
Verify that new image contains added settings.
Try doing some actions in docker that require external connectivity.
You might find [dib docs](https://docs.openstack.org/diskimage-builder/latest/user_guide/index.htmlhttps://docs.openstack.org/diskimage-builder/latest/user_guide/index.html) and [cloud init modules](https://cloudinit.readthedocs.io/en/latest/reference/modules.html) interesting, even though their knowledge is not required for completing this task

**Comment by mmskv** [comment]
Closed with 644b17597b1909bac5af0230792a5b682b1b248a
